package com.viiup.web.flock.providers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.mail.javamail.MimeMessagePreparator;
import org.springframework.stereotype.Service;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

/**
 * Created by AbdullahMoyeen on 2/3/16.
 */
@Service
public class SpringEmailProvider implements IEmailProvider {

    @Autowired
    private JavaMailSender mailSender;

    public void sendEmail() {

        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper messageHelper = new MimeMessageHelper(message, true, "UTF-8");
            messageHelper.setFrom("Flock <viiup.utd.emse@gmail.com>");
            messageHelper.setTo(new String[]{"Abdullah.Moyeen@gmail.com"});
            messageHelper.setSubject("Re: Flock Test Email (Generated by Forgot Password Link)");
            messageHelper.setText(getHtmlMessage("dynamic content<br>goes here..."), true);

            mailSender.send(message);
        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }

    private String getHtmlMessage(String messageText){

        StringBuilder htmlMessage = new StringBuilder();

        htmlMessage.append("<html>\n");
        htmlMessage.append("    <body>\n");
        htmlMessage.append("        <div style=\"background-color:darkorange; color:white; width:100%; height:80px; padding:5px; text-align:center; font-size: large;\">\n");
        htmlMessage.append("            <h1>Flock</h1>\n");
        htmlMessage.append("        </div>\n");
        htmlMessage.append("        <div style=\"background-color:gold; width:100%; height:20px; padding:5px; float:top;\">\n");
        htmlMessage.append("          \n");
        htmlMessage.append("        </div>\n");
        htmlMessage.append("        <div style=\"width:100%; height: 100px; padding:5px; float:top;\">\n");
        htmlMessage.append("            <table style=\"width:100%; font-size: large; color: black; text-align: center;border-bottom: 2px solid black;\">\n");
        htmlMessage.append("                <tr>\n");
        htmlMessage.append("                    <td style=\"text-align: center;\">\n");
        htmlMessage.append(messageText);
        htmlMessage.append("                    </td>\n");
        htmlMessage.append("                </tr>\n");
        htmlMessage.append("                <tr>\n");
        htmlMessage.append("                    <td style=\"text-align: center;\">&nbsp;</td>\n");
        htmlMessage.append("                </tr>\n");
        htmlMessage.append("            </table>\n");
        htmlMessage.append("        </div>\n");
        htmlMessage.append("    </body>\n");
        htmlMessage.append("</html>");

        return htmlMessage.toString();
    }
}